### ISSUE TITLE
Issues when running thru localhost

### ISSUE THREAD

**Issue by oscarmh** [hisashin/NinjaPCR-web#24]
Hi, I´m a proud user of NinjaPCR I have installed in a RPi4 following the instructions with "Run by Manual" and it works fine in a computer in the same network (both WIndows and Mac) works fine I connect to the NinjaPCR but from the RPI4 itself it is not possible to "connect".  Any hint ?? Thanks in advance

**Comment by oscarmh** [comment]
What I got is something like 
![imagen](https://user-images.githubusercontent.com/17768352/94301454-df86ef80-ff6a-11ea-8b5d-4058145abcbf.png)

**Comment by oscarmh** [comment]
Seems that ninjapcr.local is not resolved as a solution I´ve added local ip address to /etc/hosts but it is not a clean solution

**Comment by maripo** [comment]
Thank you for using NinjaPCR! It seems that your RPi is working well as a mDNS client but not configured as a client. 
To enable the mDNS client feature, try installing libnss-mdns by running the commands below on your RPi :

```
sudo apt-get update
sudo apt-get install libnss-mdns
```

Does this solve the connection problem?

**Comment by oscarmh** [comment]
mmm, no I´m using hosts file, some config needed in the nsswitch ? Ive added 
hosts:          files mdns4_minimal [NOTFOUND=return] dns wins mdns4

**Comment by maripo** [comment]
> hosts: files mdns4_minimal [NOTFOUND=return] dns wins mdns4

Is seems to be good if you mean /etc/nsswitch.conf.

Please try to access ninjapcr.local from the command line to make sure it's not the browser's issue.

`$ curl http://ninjapcr.local`

`$ getent hosts`

**Comment by oscarmh** [comment]
Thanks not it is working seems to be a glitch in the avahi-daemon.... needs to be restarted, thanks for the support @maripo
